name: ADF CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PACKAGE_FOLDER: 'build'
      ADF_ROOT_FOLDER: ''
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug - List Directory
        run: ls -la ${{ github.workspace }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Create Build Directory
        run: mkdir -p ${{ github.workspace }}/${{ env.PACKAGE_FOLDER }}

      - name: Create package.json
        run: |
          echo '{
            "name": "adf-ci",
            "version": "1.0.0",
            "scripts": {
              "build": "echo Build process running"
            },
            "dependencies": {}
          }' > ${{ github.workspace }}/${{ env.PACKAGE_FOLDER }}/package.json

      - name: Install npm packages
        run: npm install
        working-directory: ${{ github.workspace }}/${{ env.PACKAGE_FOLDER }}

      - name: Debug - Check if ARM Template is generated
        run: ls -la ${{ github.workspace }}/${{ env.PACKAGE_FOLDER }}/ArmTemplate || echo "ArmTemplate directory not found"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Data Factory Resources
        run: |
          npm run build validate ${{ github.workspace }}/$ADF_ROOT_FOLDER \
            /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.DATA_FACTORY_NAME }}
        working-directory: ${{ github.workspace }}/${{ env.PACKAGE_FOLDER }}

      - name: Generate ARM Template
        run: |
          set -e
          npm run build export ${{ github.workspace }}/$ADF_ROOT_FOLDER \
            /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.DATA_FACTORY_NAME }} "ArmTemplate"
        working-directory: ${{ github.workspace }}/${{ env.PACKAGE_FOLDER }}

      - name: Debug - Check if ARM Template was successfully generated
        run: ls -la ${{ github.workspace }}/${{ env.PACKAGE_FOLDER }}/ArmTemplate || echo "ArmTemplate directory not found after generation"

      - name: Upload ARM Template Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArmTemplates
          path: ${{ github.workspace }}/${{ env.PACKAGE_FOLDER }}/ArmTemplate/**
