name: ADF CI/CD Pipeline

on:  
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    uses: ./.github/workflows/adf-ci-cd-template.yml
    with:
      target_Environment: 'ALL'
    secrets: inherit
