name: ADF CI/CD Pipeline

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-DEV:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    name: Deploy to Dev
    uses: ./.github/workflows/adf-ci-cd-template.yml
    with:
      target_environment: 'Dev'
    secrets: inherit
    environment: Dev  

  deploy-to-TEST:
    needs: deploy-to-DEV
    if: github.ref == 'refs/heads/main'
    name: Deploy to Test
    uses: ./.github/workflows/adf-ci-cd-template.yml
    with:
      target_environment: 'Test'
    secrets: inherit
    environment: Test  

  deploy-to-PROD:
    needs: deploy-to-TEST
    if: github.ref == 'refs/heads/main'
    name: Deploy to Prod
    uses: ./.github/workflows/adf-ci-cd-template.yml
    with:
      target_environment: 'prod'
    secrets: inherit
    environment: production  
