name: ADF Release Pipeline

on:
  workflow_run:
    workflows: ["ADF CI Pipeline"]  # Ensure it runs after the CI pipeline
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest  # Removed `needs: build` to fix the issue
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ArmTemplate
          path: ./ArmTemplate  # Corrected download path

      - name: Debug - List Downloaded Files
        run: ls -R ./ArmTemplate  # Debugging step to verify files

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy to Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: ${{ secrets.DATA_FACTORY_NAME }}
          armTemplateFile: ./ArmTemplate/ARMTemplateForFactory.json  # Corrected path
          armTemplateParametersFile: ./ArmTemplate/ARMTemplateParametersForFactory.json  # Corrected path
