name: ADF CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PACKAGE_FOLDER: 'build'
      ADF_ROOT_FOLDER: ''
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug - List Directory
        run: ls -la ${{ github.workspace }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Create Build Directory
        run: mkdir -p build

      - name: Install npm packages
        run: npm install
        working-directory: build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Data Factory Resources
        run: |
          npm run build validate ${{ github.workspace }}/$ADF_ROOT_FOLDER \
            /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.DATA_FACTORY_NAME }}
        working-directory: build

      - name: Generate ARM Template
        run: |
          npm run build export ${{ github.workspace }}/$ADF_ROOT_FOLDER \
            /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.DATA_FACTORY_NAME }} "ArmTemplate"
        working-directory: build

      - name: Upload ARM Template Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArmTemplates
          path: build/ArmTemplate
