name: ADF CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PACKAGE_FOLDER: 'build'
      ADF_ROOT_FOLDER: ''
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install npm packages
        run: npm install
        working-directory: ${{ github.workspace }}/$PACKAGE_FOLDER

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Data Factory Resources
        run: |
          npm run build validate ${{ github.workspace }}/$ADF_ROOT_FOLDER \
            /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.DATA_FACTORY_NAME }}
        working-directory: ${{ github.workspace }}/build

      - name: Generate ARM Template
        run: |
          npm run build export ${{ github.workspace }}/$ADF_ROOT_FOLDER \
            /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.DATA_FACTORY_NAME }} "ArmTemplate"
        working-directory: ${{ github.workspace }}/build

      - name: Upload ARM Template Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ArmTemplates
          path: ${{ github.workspace }}/$PACKAGE_FOLDER/ArmTemplate
