name: ADF CI/CD Pipeline

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  call-template:
    uses: saikiran10496/ADF-Git/.github/workflows/adf-ci-cd-template.yml@main
    with:
      adf_root_folder: ''
    secrets: inherit

  release:
    needs: call-template
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: export
          path: ${{ github.workspace }}/export

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy to Dev Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: ${{ secrets.DATA_FACTORY_NAME }}
          armTemplateFile: ${{ github.workspace }}/export/ARMTemplateForFactory.json
          armTemplateParametersFile: ${{ github.workspace }}/export/ARMTemplateParametersForFactory.json

      - name: Deploy to Test Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: test-demo-ADF-githubactions
          armTemplateFile: ${{ github.workspace }}/export/ARMTemplateForFactory.json
          armTemplateParametersFile: ${{ github.workspace }}/export/ARMTemplateParametersForFactory.json

  deploy_to_prod:
    needs: release
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: export
          path: ${{ github.workspace }}/export

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy to Prod Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: prod-demo-ADF-githubactions
          armTemplateFile: ${{ github.workspace }}/export/ARMTemplateForFactory.json
          armTemplateParametersFile: ${{ github.workspace }}/export/ARMTemplateParametersForFactory.json
