name: ADF CI/CD Pipeline

on:  
  push:
    branches: [ main ]
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-dev:
    uses: ./.github/workflows/adf-ci-cd-template.yml
    with:
      adf_root_folder: ''
      data_factory_name: ${{ secrets.DATA_FACTORY_NAME }}
    secrets: inherit

  deploy-to-test:
    needs: deploy-to-dev
    uses: ./.github/workflows/adf-ci-cd-template.yml
    with:
      adf_root_folder: ''
      data_factory_name: test-demo-ADF-githubactions
    secrets: inherit

  deploy-to-prod:
    needs: deploy-to-test
    environment: production
    uses: ./.github/workflows/adf-ci-cd-template.yml
    with:
      adf_root_folder: ''
      data_factory_name: prod-demo-ADF-githubactions
    secrets: inherit
