name: ADF Release Pipeline

on:
  workflow_run:
    workflows: ["ADF CI Pipeline"] # Ensures this runs after the CI pipeline
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build  # Ensures this runs after the build job in CI
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ArmTemplate  # Ensure this matches the uploaded artifact name
          path: ./ArmTemplate  # Specify a directory to extract files

      - name: Debug - List Downloaded Files
        run: ls -R ./ArmTemplate  # Check if files are present

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy to Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: ${{ secrets.DATA_FACTORY_NAME }}
          armTemplateFile: ./ArmTemplate/ARMTemplateForFactory.json  # Correct file path
          armTemplateParametersFile: ./ArmTemplate/ARMTemplateParametersForFactory.json  # Correct file path
