name: ADF CD Pipeline

on:
  workflow_run:
    workflows: ["ADF CI Pipeline"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: Export
          path: ${{github.workspace}}/build/Export  # Ensure correct download location

      - name: Debug - Check Downloaded Files
        run: ls -R ${{github.workspace}}/Export || echo "No files found"

      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: ${{ secrets.DATA_FACTORY_NAME }}
          armTemplateFile: ${{github.workspace}}/ArmTemplate/ARMTemplateForFactory.json
          armTemplateParametersFile: ${{github.workspace}}/ArmTemplate/ARMTemplateParametersForFactory.json
