name: ADF Build and Deploy

on:
  workflow_call:
    inputs:
      adf_root_folder:
        required: false
        type: string
        default: ''
      target_Environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      RESOURCE_GROUP:
        required: true
      DATA_FACTORY_NAME:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ inputs.target_Environment == 'Dev' }}  # Only build in Dev environment

    env:
      PACKAGE_FOLDER: 'build'
      ADF_ROOT_FOLDER: ${{ inputs.adf_root_folder }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
          
      - name: Install ADF Utilities package
        run: npm install
        working-directory: ${{ github.workspace }}/build
        
      - name: Validate
        run: |
          npm run build validate ${{ github.workspace }}/$ADF_ROOT_FOLDER \
            /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.DATA_FACTORY_NAME }}
        working-directory: ${{ github.workspace }}/build

      - name: Generate ARM Template
        run: |
          npm run build export ${{ github.workspace }}/$ADF_ROOT_FOLDER \
            /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.DATA_FACTORY_NAME }} "export"
        working-directory: ${{ github.workspace }}/build
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: export
          path: ${{ github.workspace }}/build/export

  deploy:
    runs-on: ubuntu-latest
    needs: [build]  # Ensure deploy runs after build, but allow skipping
    if: ${{ always() && (inputs.target_Environment == 'Dev' || inputs.target_Environment == 'Test' || inputs.target_Environment == 'production') }}
    environment: ${{ inputs.target_Environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Download Build Artifact 
        uses: actions/download-artifact@v4
        with:
          name: export
          path: ${{ github.workspace }}/export

      - id: azure-resource-login
        name: Authenticate to Azure using UAMI
        uses: Azure/azure-resource-login-action@v1.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }
          
          
      - name: Deploy to ADF - ${{ inputs.target_Environment }}
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: ${{ secrets.DATA_FACTORY_NAME }}
          armTemplateFile: ${{ github.workspace }}/export/ARMTemplateForFactory.json
          armTemplateParametersFile: ${{ github.workspace }}/export/ARMTemplateParametersForFactory.json
