name: ADF CI/CD Pipeline

on:  
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-to-Dev:
    uses: ./.github/workflows/adf-ci-cd-template.yml
    with:
      target_Environment: 'Dev'
      adf_root_folder: ''
    secrets: inherit

  deploy-to-Test:
    needs: build-and-deploy-to-Dev  # Ensure Test depends on Dev
    uses: ./.github/workflows/adf-ci-cd-template.yml
    with:
      target_Environment: 'Test'
      adf_root_folder: ''
    secrets: inherit

  deploy-to-Prod:
    needs: deploy-to-Test  # Ensure Prod depends on Test
    uses: ./.github/workflows/adf-ci-cd-template.yml
    with:
      target_Environment: 'production'
      adf_root_folder: ''
    secrets: inherit
